version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tmsdb
      POSTGRES_USER: tms 
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tms-api:
    build: . 
    container_name: tms-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PORT: 4144   
      ALLOWED_ORIGINS: '*'      
      DB_HOST: host.docker.internal
      DB_PORT: 5454
      DB_USER: tms
      DB_PASSWORD: mysecretpassword
      DB_DATABASE: tmsdb
      BCGOV_SSO_API_URL: https://api.loginproxy.gov.bc.ca/api/v1/dev/idir/users
      BCGOV_TOKEN_URL: https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token
      BC_GOV_SSO_CLIENT_ID: client-id-here
      BCGOV_SSO_CLIENT_SECRET: client-secret-here
      LOG_LEVEL: info
    ports:
      - "4144:4144"
    networks:
      - tms_network
volumes:
  postgres_data:

networks:
  tms_network: