process.env.ALLOWED_ORIGINS = 'http://localhost:4144'
process.env.ASSERTION_EXPIRES_IN_SECONDS = '600'
process.env.ASSERTION_ISSUER = 'http://localhost:4144'
process.env.ASSERTION_KEY_ID = 'test-key'
process.env.ASSERTION_PRIVATE_KEY = 'test-private-key'
process.env.ASSERTION_PUBLIC_KEY = 'test-public-key'
process.env.BCGOV_SSO_API_CLIENT_ID = 'test-client-id'
process.env.BCGOV_SSO_API_CLIENT_SECRET = 'test-client-secret'
process.env.BCGOV_SSO_API_URL = 'http://localhost/sso'
process.env.BCGOV_SSO_API_URL_BCEID = 'http://localhost/sso/bceid'
process.env.BCGOV_TOKEN_URL = 'http://localhost/token'
process.env.ISSUER = 'http://localhost/issuer'
process.env.JWKS_URI = 'http://localhost/jwks'
process.env.LOG_LEVEL = 'error'
process.env.PORT = '4144'
process.env.POSTGRES_DATABASE = 'test'
process.env.POSTGRES_HOST = 'localhost'
process.env.POSTGRES_PASSWORD = 'test'
process.env.POSTGRES_PORT = '5432'
process.env.POSTGRES_USER = 'test'
process.env.TMS_AUDIENCE = 'test-audience'

import { loadConfig } from '../services/config.service'
loadConfig()
