global:
  config:
    dbName: app

crunchy:
  enabled: true
  postgresVersion: 17
  postGISVersion: ~
  imagePullPolicy: IfNotPresent
  shutdown: false

  # No standby
  standby:
    enabled: false

  # No disaster recovery / cloning
  clone:
    enabled: false

    s3:
      enabled: false
  # No PITR
  restore:
    enabled: false
    repoName: ~
    target: ~

  # Single PostgreSQL instance
  instances:
    name: db
    replicas: 1

    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9187'

    dataVolumeClaimSpec:
      storage: 1Gi
      storageClassName: netapp-block-standard
      walStorage: 2.0Gi

    requests:
      cpu: 50m
      memory: 128Mi

    replicaCertCopy:
      requests:
        cpu: 1m
        memory: 32Mi

    containers:
      fluentBit:
        enabled: true
        image: fluent/fluent-bit:5.0
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi

  # No backups / pgBackRest
  pgBackRest:
    enabled: false

  # No pgBouncer
  proxy:
    enabled: false

  # Keep monitoring
  pgmonitor:
    enabled: false

  patroni:
    postgresql:
      pg_hba:
        - "host all all 0.0.0.0/0 scram-sha-256"
        - "host all all ::1/128 scram-sha-256"

      parameters:
        shared_buffers: 128MB
        wal_buffers: "-1"
        min_wal_size: 64MB
        max_wal_size: 512MB
        work_mem: 4MB
        log_min_duration_statement: 1000ms
        effective_io_concurrency: 20
