# PR-specific values for the main application chart
# Ensures complete isolation between PR environments
global:
  registry: ghcr.io
  domain: apps.silver.devops.gov.bc.ca
  autoscaling: false
  secrets:
    enabled: true
    persist: false  # Don't persist secrets for PRs
  config:
    nodeEnv: development
    databaseUser: app
    dbName: app
  debug: true

backend:
  enabled: true
  replicaCount: 1
  deploymentStrategy: Recreate  # Faster for PRs
  imagePullPolicy: Always

  # Backend environment variables with proper database connection
  environment:
    port: "4144"
    allowedOrigins: "*"
    postgresHost: "{{ .Release.Name }}-bitnami-pg"
    postgresPort: "5432"
    postgresUser: "app"
    postgresDatabase: "app"
    # SSO and authentication settings
    bcgovSsoApiUrl: "https://api.loginproxy.gov.bc.ca/api/v1/dev/idir/users"
    bcgovTokenUrl: "https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token"
    bcGovSsoClientId: "client-id"  # Will be overridden by deployment
    bcgovSsoClientSecret: "secret"  # Will be overridden by deployment
    logLevel: "debug"  # Debug logging for PR environments
    tmsAudience: "tenant-management-system-6014"
    jwksUri: "https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs"
    issuer: "https://dev.loginproxy.gov.bc.ca/auth/realms/standard"

  # Resource limits for PR environments
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Disable autoscaling for PRs
  autoscaling:
    enabled: false

  # Disable PDB for PRs
  pdb:
    enabled: false

  # Backend service configuration
  service:
    type: ClusterIP
    port: 80
    targetPort: 4144  # Backend listens on port 4144

frontend:
  enabled: true
  replicaCount: 1
  deploymentStrategy: Recreate  # Faster for PRs
  imagePullPolicy: Always

  # Frontend environment variables
  environment:
    viteKeycloakClientId: tenant-management-system-6014
    viteKeycloakRealm: standard
    viteKeycloakLogoutUrl: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout
    viteKeycloakUrl: https://dev.loginproxy.gov.bc.ca/auth

  # Resource limits for PR environments
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Disable autoscaling for PRs
  autoscaling:
    enabled: false

  # Disable PDB for PRs
  pdb:
    enabled: false

  # Frontend service configuration
  service:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 3000  # Frontend listens on port 3000
        name: http

  # Ingress configuration for PR environments
  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: "edge"

# Use simple Bitnami PostgreSQL for PR environments
# Each PR gets its own isolated database instance
bitnami-pg:
  enabled: true

  # Database authentication
  auth:
    database: "app"
    username: "app"
    password: "simple-pr-password"  # Simple password for PR testing

  # Primary database configuration
  primary:
    # Minimal storage for PR environments
    persistence:
      size: "1Gi"
      storageClass: "netapp-file-standard"

    # Reduced resources for PR environments
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"

    # Disable security contexts for OpenShift compatibility
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false

  # Disable shared memory volume for resource efficiency
  shmVolume:
    enabled: false

# Disable Crunchy PostgreSQL for PR environments
# PRs use the simpler Bitnami PostgreSQL instead
crunchy:
  enabled: false