export class RoutesConstants {
    public static HEALTH = '/v1/health'
    public static CREATE_TENANTS = '/v1/tenants'
    public static ADD_TENANT_USERS = '/v1/tenants/:tenantId/users'
    public static GET_USER_TENANTS = '/v1/users/:ssoUserId/tenants'
    public static GET_TENANT_USERS = '/v1/tenants/:tenantId/users'
    public static CREATE_TENANT_ROLES = '/v1/tenants/:tenantId/roles'
    public static ASSIGN_USER_ROLES = '/v1/tenants/:tenantId/users/:tenantUserId/roles'
    public static GET_TENANT_ROLES = '/v1/tenants/:tenantId/roles'
    public static GET_USER_ROLES = '/v1/tenants/:tenantId/users/:tenantUserId/roles'
    public static UNASSIGN_USER_ROLES = '/v1/tenants/:tenantId/users/:tenantUserId/roles/:roleId'
    public static SEARCH_BC_GOV_IDIR_USERS = '/v1/users/bcgovssousers/idir/search'
    public static GET_TENANT = '/v1/tenants/:tenantId'
    public static GET_ROLES_FOR_SSO_USER = '/v1/tenants/:tenantId/ssousers/:ssoUserId/roles'
  }