export class RoutesConstants {
    public static HEALTH = '/v1/health'
    public static CREATE_TENANTS = '/v1/tenants'
    public static ADD_TENANT_USERS = '/v1/tenants/:tenantId/users'
    public static GET_USER_TENANTS = '/v1/users/:ssoUserId/tenants'
    public static GET_TENANT_USERS = '/v1/tenants/:tenantId/users'
    public static CREATE_TENANT_ROLES = '/v1/tenants/:tenantId/roles'
    public static ASSIGN_USER_ROLES = '/v1/tenants/:tenantId/users/:tenantUserId/roles'
    public static GET_TMS_ROLES = '/v1/roles'
    public static GET_USER_ROLES = '/v1/tenants/:tenantId/users/:tenantUserId/roles'
    public static UNASSIGN_USER_ROLES = '/v1/tenants/:tenantId/users/:tenantUserId/roles/:roleId'
    public static SEARCH_BC_GOV_IDIR_USERS = '/v1/users/bcgovssousers/idir/search'
    public static GET_TENANT = '/v1/tenants/:tenantId'
    public static GET_ROLES_FOR_SSO_USER = '/v1/tenants/:tenantId/ssousers/:ssoUserId/roles'
    public static UPDATE_TENANT = '/v1/tenants/:tenantId'
    public static CREATE_TENANT_REQUEST = '/v1/tenant-requests'
    public static UPDATE_TENANT_REQUEST_STATUS = '/v1/tenant-requests/:requestId/status'
    public static GET_TENANT_REQUESTS = '/v1/tenant-requests'
    public static CREATE_GROUP = '/v1/tenants/:tenantId/groups'
    public static UPDATE_GROUP = '/v1/tenants/:tenantId/groups/:groupId'
    public static ADD_GROUP_USER = '/v1/tenants/:tenantId/groups/:groupId/users'

}