{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  # Placeholder values - will be updated by the deployer workflow
  BCGOV_SSO_API_CLIENT_ID: {{ "placeholder" | b64enc | quote }}
  BCGOV_SSO_API_CLIENT_SECRET: {{ "placeholder" | b64enc | quote }}
  ISSUER: {{ "placeholder" | b64enc | quote }}
  JWKS_URI: {{ "placeholder" | b64enc | quote }}
  # Add other backend environment variables here
  NODE_ENV: {{ .Values.global.config.nodeEnv | b64enc | quote }}
  LOG_LEVEL: {{ "info" | b64enc | quote }}
{{- end }}