name: .Tests

on:
  workflow_call:
    inputs:
      ### Required
      image_tag:
        description: Image tag for containerized integration tests
        required: true
        type: string
      target:
        description: PR number, dev, test or prod
        default: ${{ github.event.number }}
        type: string

env:
  DOMAIN: apps.silver.devops.gov.bc.ca
  PREFIX: cstar-${{ inputs.target }}

permissions: {}

jobs:
  integration-tests:
    env:
      IMAGE_TAG: ${{ inputs.image_tag }}
    name: Integration
    permissions:
      checks: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - id: cache-npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Start test services
        run: docker compose -f docker-compose.yml up -d --quiet-pull --wait
        working-directory: tests/integration

      - name: Dump logs on failure
        if: failure()
        run: docker compose -f docker-compose.yml logs
        working-directory: tests/integration

      - name: Run tests
        run: |
          npm ci --ignore-scripts
          cd collection && npx bru run \
              --env default \
              --noproxy \
              --reporter-junit results.xml
        working-directory: tests/integration

      - name: Stop test services
        if: always()
        run: |
          docker compose -f docker-compose.yml down
        working-directory: tests/integration

      - uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f # v2.6.0
        if: always()
        with:
          name: Integration Tests
          path: tests/integration/collection/results.xml
          reporter: java-junit

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: bruno-test-results
          path: tests/integration/collection/results.xml

  e2e-tests:
    name: E2E
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        name: Checkout
      - uses: actions/setup-node@v6
        name: Setup Node
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        env:
          CYPRESS_BASE_URL: https://${{ env.PREFIX }}.${{ env.DOMAIN }}/
          CI: 'true'
          TERM: xterm
        run: |
          npx cypress run

      - uses: actions/upload-artifact@v6
        if: failure()
        name: upload results
        with:
          name: cypress-results
          path: |
            ./frontend/cypress/screenshots
            ./frontend/cypress/videos
          retention-days: 7

  load-tests:
    name: Load
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        name: [backend, frontend]
    steps:
      - uses: actions/checkout@v6
      - uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1.1.0
      - uses: grafana/run-k6-action@a15e2072ede004e8d46141e33d7f7dad8ad08d9d # v1.3.1
        env:
          BACKEND_URL: https://${{ env.PREFIX }}.${{ env.DOMAIN }}/api
          FRONTEND_URL: https://${{ env.PREFIX }}.${{ env.DOMAIN }}
        with:
          path: ./tests/load/${{ matrix.name }}-test.js
          flags: --vus 1 --iterations 10
