name: .Tests

on:
  workflow_call:
    inputs:
      prefix:
        description: Prefix of Endpoint
        default: dev.connect
        type: string
      domain:
        description: Domain of endpoint
        default: digital.gov.bc.ca
        type: string
      ### Required
      image_tag:
        description: Image tag for containerized integration tests
        required: true
        type: string
      target:
        description: PR number, dev, test or prod
        default: ${{ github.event.number }}-frontend
        type: string
    secrets:
      Username:
        required: true
      Password:
        required: true
      MFA_CODE:
        required: true

env:
  DOMAIN: ${{ inputs.domain }}
  PREFIX: ${{ inputs.prefix }}

permissions: {}

jobs:
  integration-tests:
    env:
      IMAGE_TAG: ${{ inputs.image_tag }}
    name: Integration
    permissions:
      checks: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - id: cache-npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Start test services
        run: docker compose -f docker-compose.yml up -d --quiet-pull --wait
        working-directory: tests/integration

      - name: Dump logs on failure
        if: failure()
        run: docker compose -f docker-compose.yml logs
        working-directory: tests/integration

      - name: Run tests
        run: |
          npm ci --ignore-scripts
          npm run test:ci
        working-directory: tests/integration

      - name: Dump logs on failure
        if: failure()
        run: docker compose -f docker-compose.yml logs
        working-directory: tests/integration

      - name: Stop test services
        if: always()
        run: |
          docker compose -f docker-compose.yml down
        working-directory: tests/integration

      - uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f # v2.6.0
        if: always()
        with:
          name: Integration Tests
          path: tests/integration/collection/results.xml
          reporter: java-junit

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: bruno-test-results
          path: tests/integration/collection/results.xml

  e2e-tests:
    name: E2E
    defaults:
      run:
        working-directory: tests/e2e
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        name: Checkout
      - uses: actions/setup-node@v6
        name: Setup Node
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: tests/e2e/package-lock.json
      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install Playwright browsers
        run: ./node_modules/.bin/playwright install --with-deps

      - name: Run Playwright tests
        run: ./node_modules/.bin/playwright test

        env:
          BASE_URL: https://${{ env.PREFIX }}.${{ env.DOMAIN }}/
          E2E_IDIR_USERNAME: ${{ secrets.Username }}
          E2E_IDIR_PASSWORD: ${{ secrets.Password }}
          E2E_MFA_CODE: ${{ secrets.MFA_CODE }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: playwright-report
          path: tests/e2e/playwright-report
          if-no-files-found: ignore

      - name: Upload Playwright screenshots on failure
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: playwright-screenshots
          path: tests/e2e/test-results
          retention-days: 7

  load-tests:
    name: Load
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        name: [backend, frontend]
    steps:
      - uses: actions/checkout@v6
      - uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1.1.0
      - uses: grafana/run-k6-action@a15e2072ede004e8d46141e33d7f7dad8ad08d9d # v1.3.1
        env:
          BACKEND_URL: https://${{ env.PREFIX }}.${{ env.DOMAIN }}/api
          FRONTEND_URL: https://${{ env.PREFIX }}.${{ env.DOMAIN }}
        with:
          path: ./tests/load/${{ matrix.name }}-test.js
          flags: --vus 1 --iterations 10
