name: gh-pages

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
  push:
    branches:
      - main

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  publish:
    permissions:
      contents: read
      pages: write
      id-token: write
    name: Publish Docs
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          cd docs-site
          npm ci
          npm run build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-site/build
