name: PR Closed

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Release target to uninstall.  expects pr or dev,test,prod,etc'
        required: true
        type: string
  workflow_call:
    inputs:
      target:
        description: 'Release target to uninstall.  expects pr or dev,test,prod,etc'
        required: true
        type: string
  pull_request:
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: ${{ github.event.number || inputs.target }}
  cancel-in-progress: true

permissions: {}

jobs:
  cleanup-silver-dev:
    name: Cleanup and Image Promotion - Silver
    uses: ./.github/workflows/.pr-close.yml
    permissions:
      packages: write
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
      oc_server: ${{ vars.OC_SERVER }}
    with:
      cleanup: helm
      cleanup_name: cstar
      environment: silver-dev 
      packages: backend frontend migrations
      target: ${{ github.event.number || inputs.target }}
  
  cleanup-gold-dev:
    name: Cleanup and Image Promotion - Gold
    uses: ./.github/workflows/.pr-close.yml
    permissions:
      packages: write
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
      oc_server: ${{ vars.OC_SERVER }}
    with:
      cleanup: helm
      cleanup_name: cstar
      environment: gold-dev 
      packages: backend frontend migrations
      target: ${{ github.event.number || inputs.target }}
  
  cleanup-golddr-dev:
    name: Cleanup and Image Promotion - Golddr
    uses: ./.github/workflows/.pr-close.yml
    permissions:
      packages: write
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
      oc_server: ${{ vars.OC_SERVER }}
    with:
      cleanup: helm
      cleanup_name: cstar
      environment: golddr-dev 
      packages: backend frontend migrations
      target: ${{ github.event.number || inputs.target }}

  cleanup-db-silver-dev: # TODO move it off to another action later.
    name: Remove DB User from Crunchy
    environment: silver-dev
    runs-on: ubuntu-24.04
    steps:
      - uses: bcgov/action-crunchy@a109166ff26880dc75676492a33b816ac0ce392f # v1.2.6
        name: Remove PR Specific User
        with:
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_token: ${{ secrets.OC_TOKEN }}
          oc_server: ${{ vars.OC_SERVER }}
          release_name: cstar-db
          values_file: charts/crunchy/values-silver-dev.yml
  
  cleanup-db-gold-dev: # TODO move it off to another action later.
    name: Remove DB User from Crunchy
    environment: gold-dev
    runs-on: ubuntu-24.04
    steps:
      - uses: bcgov/action-crunchy@a109166ff26880dc75676492a33b816ac0ce392f # v1.2.6
        name: Remove PR Specific User
        with:
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_token: ${{ secrets.OC_TOKEN }}
          oc_server: ${{ vars.OC_SERVER }}
          release_name: cstar-db
          values_file: charts/crunchy/values-gold-dev.yml
  
  cleanup-db-golddr-dev: # TODO move it off to another action later.
    name: Remove DB User from Crunchy
    environment: golddr-dev
    runs-on: ubuntu-24.04
    steps:
      - uses: bcgov/action-crunchy@a109166ff26880dc75676492a33b816ac0ce392f # v1.2.6
        name: Remove PR Specific User
        with:
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_token: ${{ secrets.OC_TOKEN }}
          oc_server: ${{ vars.OC_SERVER }}
          release_name: cstar-db
          values_file: charts/crunchy/values-golddr-dev.yml
