name: PR Closed

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Release target to uninstall.  expects pr or dev,test,prod,etc'
        required: true
        type: string
      force_cleanup:
        description: 'Force database cleanup.  Sometimes we want to keep the db'
        required: false
        type: string
        default: true
  workflow_call:
    inputs:
      target:
        description: 'Release target to uninstall.  expects pr or dev,test,prod,etc'
        required: true
        type: string
  pull_request:
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: ${{ github.event.number || inputs.target }}
  cancel-in-progress: true

permissions: {}

jobs:
  remove-staging-dev:
    name: Remove App + Database 
    environment: staging-dev
    runs-on: ubuntu-24.04
    steps:
      - name: Helm Uninstall
        uses: bcgov/action-oc-runner@d2fc921aaa9d70684c186dbb7754e6985d44d86f # v1.4.1
        with:
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_token: ${{ secrets.oc_token }}
          oc_server: ${{ vars.oc_server }}
          commands: |
            helm uninstall ${{ github.event.number || inputs.target }}
