---
name: Deploy Dev (Silver)
permissions: {}

on:
  workflow_dispatch:
    inputs:
      autoscaling:
        description: 'enable or disable autoscaling'
        required: false
        type: boolean
        default: false 
      tag:
        description: 'Image tag set to deploy; e.g. PR number or prod'
        type: string
        default: 'latest'
      db_user:
        description: "database user; e.g. PR number or approxy"
        required: false
        type: string
        default: "appproxy"
      params:
        description: Extra parameters to pass to helm upgrade
        required: false
        type: string
  workflow_call:
    inputs:
      autoscaling:
        description: 'enable or disable autoscaling'
        required: false
        type: boolean
        default: false 
      tag:
        description: 'Image tag set to deploy; e.g. PR number or prod'
        required: false
        type: string
        default: 'latest'
      db_user:
        description: "database user; e.g. PR number or appproxy"
        required: false
        type: string
        default: "appproxy"
      params:
        description: Extra parameters to pass to helm upgrade
        required: false
        type: string
jobs:
  deploy-silver-dev:
    name: Deploys Dev (Silver)
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      environment: silver-dev
      db_user: ${{ inputs.db_user }} # appproxy is the user which works with pgbouncer.
      db_triggers: ('charts/crunchy/')
      params: 
        --set global.autoscaling=${{ inputs.autoscaling }}
        --set frontend.deploymentStrategy=RollingUpdate
        --set frontend.autoscaling.enabled=${{ inputs.autoscaling }}
        --set frontend.pdb.enabled=true
        --set frontend.pdb.minAvailable=2
        --set frontend.replicaCount=3
        --set backend.autoscaling.enabled=${{ inputs.autoscaling }}
        --set backend.deploymentStrategy=RollingUpdate
        --set backend.pdb.enabled=true
        --set backend.pdb.minAvailable=2
        --set backend.replicaCount=3
        --set global.domain="apps.silver.devops.gov.bc.ca"
        ${{ inputs.params }}
      tag: ${{ inputs.tag }}
